/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2018-01-10 07:30:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Department_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>Anjular JS Demo</title>\r\n");
      out.write("    <!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css\" integrity=\"sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb\" crossorigin=\"anonymous\">\r\n");
      out.write("  \t<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("  \t<script src=\"https://ajax.googleapis.com/ajax/libs/angularjs/1.4.3/angular.min.js\"></script>\r\n");
      out.write("  \t <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    var app = angular.module('myApp', []);\r\n");
      out.write("\tapp.controller('myCtrl', function($scope, $http) {\r\n");
      out.write("\t\t   $scope.deps;\r\n");
      out.write("\t     \t$scope.baseUrl='http://localhost:8085/SpringMVCHibernate/';\r\n");
      out.write("\t\t   $scope.departments = {};\r\n");
      out.write("\t\t   $scope.employeeList={};\r\n");
      out.write("\t\t   getUserDetails();\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t   function getUserDetails() {\r\n");
      out.write("\t\t    $http({\r\n");
      out.write("\t\t     method : 'GET',\r\n");
      out.write("\t\t     url : $scope.baseUrl+'department'\r\n");
      out.write("\t\t    }).then(function successCallback(response) {\r\n");
      out.write("\t\t     $scope.departments = response.data;\r\n");
      out.write("\t\t    }, function errorCallback(response) {\r\n");
      out.write("\t\t      console.log(\"error angular\");\r\n");
      out.write("\t\t     console.log(response.statusText);\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t   $scope.getdeartment = function(index) {\r\n");
      out.write("\t\t\t //  $scope.deps={};\r\n");
      out.write("\t\t\t   $http({\r\n");
      out.write("\t\t\t\t     method : 'GET',\r\n");
      out.write("\t\t\t\t     url : $scope.baseUrl+'department/'+index\r\n");
      out.write("\t\t\t\t    }).then(function successCallback(response) {\r\n");
      out.write("\t\t\t\t    \t\r\n");
      out.write("\t\t\t\t     $scope.deps = response.data;\r\n");
      out.write("\t\t\t\t    // alert($scope.deps.departmentName);\r\n");
      out.write("\t\t\t\t    }, function errorCallback(response) {\r\n");
      out.write("\t\t\t\t    \talert(response.status);\r\n");
      out.write("\t\t\t\t      console.log(\"error angular\");\r\n");
      out.write("\t\t\t\t     console.log(response.statusText);\r\n");
      out.write("\t\t\t\t    });\r\n");
      out.write("\t\t\t\t   }\r\n");
      out.write("\t\t   $scope.removeDepartment = function(index) {\r\n");
      out.write("\t\t\t\t //  $scope.deps={};\r\n");
      out.write("\t\t\t\t   $http({\r\n");
      out.write("\t\t\t\t\t     method : 'DELETE',\r\n");
      out.write("\t\t\t\t\t     url : $scope.baseUrl+'department/'+index\r\n");
      out.write("\t\t\t\t\t    }).then(function successCallback(response) {\r\n");
      out.write("\t\t\t\t\t    \t\r\n");
      out.write("\t\t\t\t\t     $scope.deleteStatus = response.status;\r\n");
      out.write("\t\t\t\t\t     if($scope.deleteStatus==200){\r\n");
      out.write("\t\t\t\t\t\t     alert(\"You have successfully deleted department\")\r\n");
      out.write("\t\t\t\t\t\t     }\r\n");
      out.write("\t\t\t\t\t    // alert($scope.deps.departmentName);\r\n");
      out.write("\t\t\t\t\t    }, function errorCallback(response) {\r\n");
      out.write("\t\t\t\t\t    \talert(response.status);\r\n");
      out.write("\t\t\t\t\t      console.log(\"error angular\");\r\n");
      out.write("\t\t\t\t\t     console.log(response.statusText);\r\n");
      out.write("\t\t\t\t\t    });\r\n");
      out.write("\t\t\t\t\t   }\r\n");
      out.write("\t\t   $scope.getEmployeeList = function(index) {\r\n");
      out.write("\t\t\t\t   $http({\r\n");
      out.write("\t\t\t\t\t     method : 'GET',\r\n");
      out.write("\t\t\t\t\t     url : $scope.baseUrl+'employeeList/'+index\r\n");
      out.write("\t\t\t\t\t    }).then(function successCallback(response) {\r\n");
      out.write("\t\t\t\t\t    \t  $scope.employeeList = response.data;\r\n");
      out.write("\t\t\t\t\t    // alert($scope.deps.departmentName);\r\n");
      out.write("\t\t\t\t\t    }, function errorCallback(response) {\r\n");
      out.write("\t\t\t\t\t    \talert(response.status);\r\n");
      out.write("\t\t\t\t\t      console.log(\"error angular\");\r\n");
      out.write("\t\t\t\t\t     console.log(response.statusText);\r\n");
      out.write("\t\t\t\t\t    });\r\n");
      out.write("\t\t\t\t\t   }\r\n");
      out.write("\t\t  });\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body ng-app=\"myApp\" ng-controller=\"myCtrl\">\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("     <div>\r\n");
      out.write("       <label style=\"font-size:30px;text-align: center\">Department Details</label>\r\n");
      out.write("       <table class=\"table table-striped\">\r\n");
      out.write("            <thead>\r\n");
      out.write("              <tr style=\"background-color: lightyellow;\">\r\n");
      out.write("                <th>Sl No.</th>\r\n");
      out.write("                <th>Department Name</th>\r\n");
      out.write("                <th>Description</th>\r\n");
      out.write("                <th>View Details</th>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("              <tr ng-repeat=\"department in departments\">\r\n");
      out.write("                <td> {{ $index+1 }}.</td>\r\n");
      out.write("                <td> {{department.departmentName}} </td>\r\n");
      out.write("                <td>{{department.description}}</td>\r\n");
      out.write("                <td><button style=\"font-size:24px;border: hidden;\" ng-click=\"getdeartment(department.id)\"><i class=\"fa fa-eye\" style=\"font-size:18px;\"></i></button></td>\r\n");
      out.write("              </tr>\t\t      \r\n");
      out.write("            </tbody>\r\n");
      out.write("          </table>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div ng-hide=\"!deps\">\r\n");
      out.write("           <h4 align=\"center\">Department/Employee Update</h4>\r\n");
      out.write("       <table class=\"table table-striped\">\r\n");
      out.write("            <thead>\r\n");
      out.write("              <tr style=\"background-color: lightyellow;\">\r\n");
      out.write("                <th>Department ID</th>\r\n");
      out.write("                <th>Name</th>\r\n");
      out.write("                <th>Description</th>\r\n");
      out.write("                <th>Delete</th>\r\n");
      out.write("                <th>Employees</th>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("              <tr >\r\n");
      out.write("                <td> {{ deps.id }}.</td>\r\n");
      out.write("                <td> {{deps.departmentName}} </td>\r\n");
      out.write("                <td>{{deps.description}}</td>\r\n");
      out.write("                <td><button style=\"font-size:24px;border: hidden;\" ng-click=\"removeDepartment(deps.id)\"><i class=\"fa fa-trash-o\" style=\"font-size:16px\"></i></i></button></td>\r\n");
      out.write("                 <td><button style=\"font-size:24px;border: hidden;\" ng-click=\"getEmployeeList(deps.id)\"><i class=\"fa fa-group\" style=\"font-size:16px\"></i></button></td>\r\n");
      out.write("              </tr>\t\t      \r\n");
      out.write("            </tbody>\r\n");
      out.write("          </table>\r\n");
      out.write("          </div>\r\n");
      out.write("      <div ng-hide=\"!employeeList.length\">\r\n");
      out.write("           <div>\r\n");
      out.write("          <h4 align=\"center\">Employees Details</h4>\r\n");
      out.write("           </div>\r\n");
      out.write("         <table class=\"table table-striped\">\r\n");
      out.write("            <thead>\r\n");
      out.write("              <tr style=\"background-color: lightyellow;\">\r\n");
      out.write("                <th>Employee ID</th>\r\n");
      out.write("                <th>Name</th>\r\n");
      out.write("                <th>DOB</th>\r\n");
      out.write("                <th>Update</th>\r\n");
      out.write("                <th>Remove</th>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </thead>\r\n");
      out.write("            <tbody>\r\n");
      out.write("              <tr ng-repeat=\"employee in employeeList\">\r\n");
      out.write("                <td> {{ employee.id }}.</td>\r\n");
      out.write("                <td> {{employee.employeeName}} </td>\r\n");
      out.write("                <td>{{employee.dob}}</td>\r\n");
      out.write("                 <td><button style=\"font-size:14px;border: hidden;\"  data-toggle=\"modal\" data-target=\"#myModal\"><i class=\"fa fa-edit\" style=\"font-size:16px\"></i></button></td>\r\n");
      out.write("                 <td><button style=\"font-size:14px;border: hidden;\" ng-click=\"\"><i class=\"fa fa-trash-o\" style=\"font-size:16px\"></i></button></td>\r\n");
      out.write("              </tr>\t\t      \r\n");
      out.write("            </tbody>\r\n");
      out.write("          </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("        <!--  -->\r\n");
      out.write("       <div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\r\n");
      out.write("    <div class=\"modal-dialog\">\r\n");
      out.write("    \r\n");
      out.write("      <!-- Modal content-->\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <div class=\"modal-header\">\r\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("          <h4 class=\"modal-title\">Modal Header</h4>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-body\">\r\n");
      out.write("          <p>Some text in the modal.</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"modal-footer\">\r\n");
      out.write("          <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("        \r\n");
      out.write("       <!-- Modal -->\r\n");
      out.write("    <div id=\"myModalEdit\" class=\"modal fade\" role=\"dialog\">\r\n");
      out.write("      <div class=\"modal-dialog\">\r\n");
      out.write("    \r\n");
      out.write("        <!-- Modal content-->\r\n");
      out.write("        <div class=\"modal-content\">\r\n");
      out.write("          <div class=\"modal-header\">\r\n");
      out.write("            <h4 class=\"modal-title\">Employee Details</h4>\r\n");
      out.write("            <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"modal-body\">\r\n");
      out.write("            <form class=\"form-horizontal\">\r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label for=\"inputEmailEid\" class=\"col-sm-2 control-label\">Employee ID</label>\r\n");
      out.write("                <div class=\"col-sm-10\">\r\n");
      out.write("                  <input type=\"text\" class=\"form-control\" id=\"inputEmailEid\" ng-model=\"clickedUser.username\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("    \r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label for=\"inputEmailName\" class=\"col-sm-2 control-label\">Name</label>\r\n");
      out.write("                <div class=\"col-sm-10\">\r\n");
      out.write("                  <input type=\"text\" class=\"form-control\" id=\"inputEmailName\"  ng-model=\"clickedUser.email\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("    \r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <label for=\"inputEmailDOB\" class=\"col-sm-2 control-label\">DOB</label>\r\n");
      out.write("                <div class=\"col-sm-10\">\r\n");
      out.write("                  <input type=\"text\" class=\"form-control\" id=\"inputEmailDOB\" ng-model=\"clickedUser.fullName\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("                            \r\n");
      out.write("              <div class=\"form-group\">\r\n");
      out.write("                <div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("                  <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Done</button>\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </form>\r\n");
      out.write("          </div>\r\n");
      out.write("          <div class=\"modal-footer\">\r\n");
      out.write("              \r\n");
      out.write("            <button type=\"button\" class=\"btn btn-default\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
